apiVersion: v1
kind: Service
metadata:
  name: hello-deployment-svc
spec:
  selector:
    app: hello-deployment
  ports:
    - name: http
      port: 80
      protocol: TCP
      targetPort: 8080
  type: LoadBalancer
